services:
    app:
        build: .
        volumes:
            - .:/var/www/html
        command: sh -c "chmod -R 777 storage bootstrap/cache && php-fpm"
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        restart: unless-stopped
