version: "3.8"

services:
    app:
        build: .
        volumes:
            - .:/var/www/html
            - ./.env:/var/www/html/.env
        command: sh -c "chmod -R 777 storage bootstrap/cache && php-fpm"
        restart: unless-stopped
        ports:
            - "9000:9000"
        depends_on:
            - db

    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: bodyquick
            MYSQL_ROOT_PASSWORD: C@rlota1
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mysql-init:/docker-entrypoint-initdb.d

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        restart: unless-stopped

volumes:
    db_data:
